Repository zouhir96/Portfolio, pull requests merged in 2024-07, with the labels that each got.

#7 release 1.0.0
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/Vector.png
  public/logo.png
  public/portfolio/project1.png
  public/portfolio/project2.png
  public/portfolio/project3.png
  public/zouhir.png
  src/components/educationItem.jsx
  src/components/experienceItem.jsx
  src/components/index.js
  src/components/portfolioItem.jsx
  src/components/sectionHeading.jsx
  src/index.css
  src/views/About/about.jsx
  src/views/Contact/contact.jsx
  src/views/Contact/index.js
  src/views/Hero/hero.jsx
  src/views/NavBar/navBar.jsx
  src/views/Portfolio/portfolio.jsx
  src/views/Skills/skills.jsx
  src/views/main.jsx
  tailwind.config.js
Labels: release

#8 feat: Create deploy workflow.
  .github/workflows/deploy
Labels: feature

#9 release 1.0.0
  .github/workflows/deploy
  src/components/sectionHeading.jsx
  src/views/Contact/contact.jsx
  src/views/NavBar/navBar.jsx
Labels: release

#11 feature: Add loading and toast + ui enhancements.
  package-lock.json
  package.json
  public/cv_zouhir_rajdaoui.pdf
  src/components/portfolioItem.jsx
  src/views/Contact/contact.jsx
  src/views/Hero/hero.jsx
  src/views/NavBar/navBar.jsx
  src/views/Portfolio/portfolio.jsx
  src/views/Skills/skills.jsx
  src/views/main.jsx
  tailwind.config.js
Labels: enhancement
